# Numpy

In [2]:
import numpy as np

# Creating Arrays

In [4]:
mylist = [4,5,6]
x = np.array(mylist)
x

array([4, 5, 6])

In [6]:
y = np.array([4,5,6]) #directly pass array 
y

array([4, 5, 6])

In [8]:
z = np.array(([7,8,9],[10,11,12])) #multidimension array 
z

array([[ 7,  8,  9],
       [10, 11, 12]])

In [9]:
z.shape #gives shape of array 

(2, 3)

In [17]:
n = np.arange(0, 30, 2) #Generates array with start, stop, and interval 
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [19]:
n = n.reshape(3, 5) #reshapes array into 3 by 5 arrangement 
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [27]:
o = np.linspace(0, 4, 9) #generates list with start, stop, and interval number 
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [28]:
o.resize(3, 3) #resize changes the dimensions in place 
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [29]:
np.array([1, 2, 3] * 3) #create an array with repeating list 

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [30]:
np.repeat([1, 2, 3], 3) #repeat elements in array

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [31]:
p = np.ones([2, 3], int) #generate ones array
p

array([[1, 1, 1],
       [1, 1, 1]])

In [32]:
np.vstack([p, 2*p]) #vertically stack arrays

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [33]:
np.hstack([p, 2*p]) #horizontal stack of arrays

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operations 

In [34]:
x + y

array([ 8, 10, 12])

In [35]:
x*y

array([16, 25, 36])

In [36]:
x.dot(y)

77

# Indexing and Slicing 

In [37]:
s = np.arange(13)**2 #generate square of 0 to 12
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [39]:
s[0], s[4], s[-1], s[0:3] #index specific elements

(0, 16, 144, array([0, 1, 4]))

In [47]:
n = np.arange(36) #generates array 0 to 35
n.resize(6,6)
n

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [48]:
n[2,2] #grabs specific element

14

In [49]:
n[3,3:6] #specific row and elements in row 

array([21, 22, 23])

In [51]:
n[-1, :: 2] #last row every other element

array([30, 32, 34])

In [52]:
n[n > 30] #grab all elements greater than 30

array([31, 32, 33, 34, 35])

In [54]:
n[n > 30] = 30 #convert all elements greater than 30 to 30
n

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [60]:
n2 = n[:3, :3] #grab first three row and first three columns
n2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [62]:
n2[:] = 0 #set all elements to zero 
n2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [64]:
n #note elements in original array have changed

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [66]:
n_copy = n.copy() #creates a copy of original array

In [67]:
n_copy[:] = 10 #set all elements to 10
print(n_copy)
print()
print(n)


[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


# Iterating over arrays

In [71]:
test = np.random.randint(0, 10, (4,3))#creates random array with dimensions 4 by 3
test

array([[2, 3, 6],
       [2, 7, 2],
       [3, 4, 0],
       [7, 5, 0]])

In [76]:
for row in test: #print rows, here 'row" is just an index 
    print(row)

[2 3 6]
[2 7 2]
[3 4 0]
[7 5 0]


In [79]:
for i in range(len(test)): #generates a length that corresponds to array 
    print(test[i])                 #print index for rows and columns

[2 3 6]
[2 7 2]
[3 4 0]
[7 5 0]


In [81]:
test2 = test**2 #square previous array
test2

array([[ 4,  9, 36],
       [ 4, 49,  4],
       [ 9, 16,  0],
       [49, 25,  0]])

In [84]:
for i, j in zip(test,test2): #using zip to iterate through two arrays and printing addition
    print(i, '+',  j,  '=',  i + j )

[2 3 6] + [ 4  9 36] = [ 6 12 42]
[2 7 2] + [ 4 49  4] = [ 6 56  6]
[3 4 0] + [ 9 16  0] = [12 20  0]
[7 5 0] + [49 25  0] = [56 30  0]


In [8]:
n = np.arange(0,36,1) #generates array 0 to 35
n.resize(6,6)
n

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [9]:
n.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [10]:
n

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [11]:
n[[2,3],[2,3]]

array([14, 21])

In [12]:
n[2::2,2::2]


array([[14, 16],
       [26, 28]])